### ISSUE TITLE
Using the role

### ISSUE THREAD

**Issue by eldudemeister** [constructorfleet/ansible-ble-monitor#1]
Hi, I’m pretty new to Ansible but have some small playbooks set up. I’ve got Monitor set up on a couple of Pi’s but would like to use your playbook going forward. Not sure the best way of doing this but wondered if you had considered putting it on ansible galaxy?

**Comment by Teagan42** [comment]
For now you can add the role and install via galaxy with:

`roles/requirements.yml`
```yaml
---

- src: https://github.com/constructorfleet/ansible-ble-monitor.git
  name: ble-monitor
  version: v0.25
```

```shell
ansible-galaxy install -r roles/requirements.yml
```

We have a lot of ansible roles we use for our homelab, haven't thought too much about an account with galaxy - but it's not a bad suggestion. Thank you.

**Comment by eldudemeister** [comment]
Awesome, thanks so much! Having a play with the role now!

**Comment by eldudemeister** [comment]
Sorry just one last question, where do you specify the known static addresses for phones? I know where it is in monitor usually but wasnt sure where it gets specified in the ansible role?

**Comment by Teagan42** [comment]
```yaml
---
# group_vars/ble_monitor/vars.yml

known_devices:
  - name: Bob's Phone
    mac: 00:00:00:00:00:00
  - name: Jim's Phone
    mac: 10:00:00:00:00:00
```
